import BitkitCore
import SwiftUI

struct LegacyRnRecoveryScreen: View {
    @Environment(\.dismiss) private var dismiss
    @EnvironmentObject private var app: AppViewModel
    @EnvironmentObject private var wallet: WalletViewModel

    @State private var indexLimit = "10000"
    @State private var scanResult: LegacyRnCloseRecoveryScanResult?
    @State private var sweepPreview: LegacyRnCloseRecoverySweepPreview?
    @State private var broadcastTxid: String?
    @State private var errorMessage: String?
    @State private var isScanning = false
    @State private var isPreparing = false
    @State private var isBroadcasting = false

    private var parsedIndexLimit: UInt32? {
        let trimmed = indexLimit.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let value = UInt32(trimmed), value > 0 else { return nil }
        return value
    }

    private var isBusy: Bool {
        isScanning || isPreparing || isBroadcasting
    }

    private var canScan: Bool {
        parsedIndexLimit != nil && !isBusy
    }

    private var hasResult: Bool {
        scanResult != nil || sweepPreview != nil || broadcastTxid != nil
    }

    private func currentElectrumServerUrl() -> String {
        ElectrumConfigService().getCurrentServer().fullUrl
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            NavigationBar(title: "Legacy Recovery")
                .padding(.horizontal, 16)

            if let broadcastTxid {
                successPage(txid: broadcastTxid)
            } else {
                ScrollView(showsIndicators: false) {
                    VStack(alignment: .leading, spacing: 24) {
                        scanSection

                        if let errorMessage {
                            messageSection(
                                title: "Error",
                                message: errorMessage,
                                color: .redAccent
                            )
                        }

                        if let sweepPreview {
                            previewSection(sweepPreview)
                        } else if let scanResult {
                            if scanResult.outputsCount == 0 {
                                noFundsSection
                            } else {
                                foundSection(scanResult)
                            }
                        }
                    }
                    .padding(.horizontal, 16)
                    .bottomSafeAreaPadding()
                }
            }
        }
        .navigationBarHidden(true)
        .onChange(of: indexLimit) { _, newValue in
            let filtered = newValue.filter(\.isNumber)
            if filtered != newValue {
                indexLimit = filtered
            }
        }
    }

    private var scanSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            VStack(alignment: .leading, spacing: 8) {
                SettingsSectionHeader("SCAN")

                BodySText(
                    "Scan for native SegWit outputs generated by the legacy channel-close path.",
                    textColor: .textSecondary
                )

                TextField("10000", text: $indexLimit)
                    .keyboardType(.numberPad)
                    .textInputAutocapitalization(.never)
                    .autocorrectionDisabled()
                    .padding(.horizontal, 16)
                    .frame(height: 50)
                    .background(Color.white08)
                    .cornerRadius(8)
                    .accessibilityIdentifier("LegacyRnRecoveryIndexLimit")

                FootnoteText("Index limit")
            }

            if !hasResult {
                CustomButton(
                    title: "Scan",
                    isDisabled: !canScan,
                    isLoading: isScanning,
                    shouldExpand: true
                ) {
                    await scan()
                }
                .accessibilityIdentifier("LegacyRnRecoveryScan")
            }
        }
    }

    private func foundSection(_ result: LegacyRnCloseRecoveryScanResult) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            SettingsSectionHeader("FUNDS FOUND")

            VStack(spacing: 0) {
                SettingsRow(
                    title: "Total",
                    rightText: formattedSats(result.totalAmount),
                    rightIcon: nil
                )
                SettingsRow(
                    title: "Outputs",
                    rightText: "\(result.outputsCount)",
                    rightIcon: nil
                )
            }

            CustomButton(
                title: "Prepare Sweep",
                isDisabled: isBusy,
                isLoading: isPreparing,
                shouldExpand: true
            ) {
                await prepareSweep()
            }
            .accessibilityIdentifier("LegacyRnRecoveryPrepare")

            CustomButton(
                title: "Scan Again",
                variant: .secondary,
                isDisabled: isBusy,
                shouldExpand: true
            ) {
                await scan()
            }
        }
    }

    private var noFundsSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            messageSection(
                title: "No Funds Found",
                message: "No legacy native SegWit close outputs were found up to index \(indexLimit).",
                color: .textPrimary
            )

            CustomButton(
                title: "Scan Again",
                variant: .secondary,
                isDisabled: isBusy,
                shouldExpand: true
            ) {
                await scan()
            }
        }
    }

    private func previewSection(_ preview: LegacyRnCloseRecoverySweepPreview) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            SettingsSectionHeader("CONFIRM SWEEP")

            VStack(spacing: 0) {
                SettingsRow(
                    title: "Receive",
                    rightText: formattedSats(preview.amountAfterFees),
                    rightIcon: nil
                )
                SettingsRow(
                    title: "Network Fee",
                    rightText: formattedSats(preview.estimatedFee),
                    rightIcon: nil
                )
                SettingsRow(
                    title: "Inputs",
                    rightText: "\(preview.outputsCount)",
                    rightIcon: nil
                )
                SettingsRow(
                    title: "To",
                    rightText: shortened(preview.destinationAddress),
                    rightIcon: nil
                )
                SettingsRow(
                    title: "Tx",
                    rightText: shortened(preview.txid),
                    rightIcon: nil
                )
            }

            CustomButton(
                title: "Broadcast Sweep",
                isDisabled: isBusy,
                isLoading: isBroadcasting,
                shouldExpand: true
            ) {
                await broadcastSweep()
            }
            .accessibilityIdentifier("LegacyRnRecoveryBroadcast")

            CustomButton(
                title: "Scan Again",
                variant: .secondary,
                isDisabled: isBusy,
                shouldExpand: true
            ) {
                await scan()
            }
        }
    }

    private func successPage(txid: String) -> some View {
        VStack(alignment: .leading, spacing: 0) {
            ScrollView(showsIndicators: false) {
                VStack(alignment: .leading, spacing: 24) {
                    scanSection

                    if let errorMessage {
                        messageSection(
                            title: "Error",
                            message: errorMessage,
                            color: .redAccent
                        )
                    }

                    successSection(txid: txid)
                }
                .padding(.horizontal, 16)
                .padding(.bottom, 24)
            }

            CustomButton(title: "Done", shouldExpand: true) {
                dismiss()
            }
            .padding(.horizontal, 16)
            .padding(.top, 12)
        }
        .bottomSafeAreaPadding()
        .frame(maxHeight: .infinity, alignment: .top)
    }

    private func successSection(txid: String) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            SettingsSectionHeader("SWEEP COMPLETE")

            VStack(spacing: 0) {
                SettingsRow(
                    title: "Tx",
                    rightText: shortened(txid),
                    rightIcon: nil
                )
            }

            BodySText(
                "The sweep transaction was broadcast. The funds will appear after the wallet syncs and the transaction confirms.",
                textColor: .textSecondary
            )
        }
    }

    private func messageSection(title: String, message: String, color: Color) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            SettingsSectionHeader(title.localizedUppercase)
            BodySText(message, textColor: color)
        }
    }

    @MainActor
    private func scan() async {
        guard let limit = parsedIndexLimit else {
            errorMessage = "Enter a valid index limit."
            return
        }

        isScanning = true
        errorMessage = nil
        scanResult = nil
        sweepPreview = nil
        broadcastTxid = nil
        defer { isScanning = false }

        do {
            scanResult = try await CoreService.shared.utility.scanLegacyRnNativeSegwitRecoveryFunds(
                indexLimit: limit,
                electrumUrl: currentElectrumServerUrl()
            )
        } catch {
            Logger.error(error, context: "LegacyRnRecoveryScreen.scan")
            errorMessage = error.localizedDescription
        }
    }

    @MainActor
    private func prepareSweep() async {
        guard let limit = parsedIndexLimit else {
            errorMessage = "Enter a valid index limit."
            return
        }

        isPreparing = true
        errorMessage = nil
        sweepPreview = nil
        defer { isPreparing = false }

        do {
            if wallet.onchainAddress.isEmpty {
                try await wallet.refreshBip21()
            }
            guard !wallet.onchainAddress.isEmpty else {
                throw AppError(message: "Destination address unavailable", debugMessage: nil)
            }

            let feeRate = (try? await CoreService.shared.blocktank.fees(refresh: false))
                .map { TransactionSpeed.normal.getFeeRate(from: $0) }

            sweepPreview = try await CoreService.shared.utility.prepareLegacyRnNativeSegwitRecoverySweep(
                destinationAddress: wallet.onchainAddress,
                feeRateSatsPerVbyte: feeRate,
                indexLimit: limit,
                electrumUrl: currentElectrumServerUrl()
            )
        } catch {
            Logger.error(error, context: "LegacyRnRecoveryScreen.prepareSweep")
            errorMessage = error.localizedDescription
        }
    }

    @MainActor
    private func broadcastSweep() async {
        guard let sweepPreview else { return }

        isBroadcasting = true
        errorMessage = nil
        defer { isBroadcasting = false }

        do {
            let txid = try await CoreService.shared.utility.broadcastRawTx(
                txHex: sweepPreview.txHex,
                electrumUrl: currentElectrumServerUrl()
            )
            broadcastTxid = txid
            await wallet.syncStateAsync()
            app.toast(type: .success, title: "Sweep Broadcast", description: shortened(txid))
        } catch {
            Logger.error(error, context: "LegacyRnRecoveryScreen.broadcastSweep")
            errorMessage = error.localizedDescription
        }
    }

    private func formattedSats(_ sats: UInt64) -> String {
        "\(CurrencyFormatter.formatSats(sats)) sats"
    }

    private func shortened(_ value: String) -> String {
        guard value.count > 24 else { return value }
        return "\(value.prefix(10))...\(value.suffix(10))"
    }
}

#Preview {
    LegacyRnRecoveryScreen()
        .environmentObject(AppViewModel())
        .environmentObject(WalletViewModel())
        .preferredColorScheme(.dark)
}
