name: Bug Report
description: Report a bug in Bitkit iOS
type: bug
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug and what you expected instead
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to...
        2. Tap on...
        3. See error
    validations:
      required: false

  - type: textarea
    id: evidence
    attributes:
      label: Logs / Screenshots / Recordings
      placeholder: Drag and drop files here
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: e.g., v2.0.0, iPhone 15 Pro, iOS 17, mainnet
    validations:
      required: false
