name: Bug Report
description: Report a bug in Bitkit iOS
type: bug
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen instead?
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to...
        2. Tap on...
        3. See error
    validations:
      required: false

  - type: textarea
    id: evidence
    attributes:
      label: Logs / Screenshots / Recordings
      placeholder: Drag and drop files here
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Bitkit Version
      placeholder: e.g., 2.0.0
    validations:
      required: false

  - type: input
    id: device
    attributes:
      label: Device / OS
      placeholder: e.g., iPhone 15 Pro, iOS 17.4
    validations:
      required: false

  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      options:
        - label: Mainnet
        - label: Regtest
        - label: Local

  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      options:
        - Always
        - Often (>50%)
        - Sometimes (<50%)
        - Rarely (once or twice)
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: |
        Any other context about the problem, e.g.:
        - New wallet / Restored from backup / Migrated from RN
        - Lightning or on-chain related
        - Specific channel state
    validations:
      required: false
