name: Feature Request
description: Suggest a new feature or improvement
type: feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      placeholder: What problem does this solve? Why do you need this?
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Describe what you'd like to happen
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any workarounds or alternative solutions you've thought of?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Screenshots, mockups, links, or any other context
    validations:
      required: false
