// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(PubkySDKFFI)
import PubkySDKFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pubky_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pubky_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol KeyProvider : AnyObject {
    
    func secretKey() throws  -> [UInt8]
    
}

public class KeyProviderImpl:
    KeyProvider {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_fn_clone_keyprovider(self.pointer, $0) }
    }

    deinit {
        try! rustCall { uniffi_pubky_fn_free_keyprovider(pointer, $0) }
    }

    

    
    
    public func secretKey() throws  -> [UInt8] {
        return try  FfiConverterSequenceUInt8.lift(
            try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_keyprovider_secret_key(self.uniffiClonePointer(), $0
    )
}
        )
    }

}
fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate typealias UniFFICallbackHandle = UInt64
fileprivate class UniFFICallbackHandleMap<T> {
    private var leftMap: [UniFFICallbackHandle: T] = [:]
    private var counter: [UniFFICallbackHandle: UInt64] = [:]
    private var rightMap: [ObjectIdentifier: UniFFICallbackHandle] = [:]

    private let lock = NSLock()
    private var currentHandle: UniFFICallbackHandle = 1
    private let stride: UniFFICallbackHandle = 1

    func insert(obj: T) -> UniFFICallbackHandle {
        lock.withLock {
            let id = ObjectIdentifier(obj as AnyObject)
            let handle = rightMap[id] ?? {
                currentHandle += stride
                let handle = currentHandle
                leftMap[handle] = obj
                rightMap[id] = handle
                return handle
            }()
            counter[handle] = (counter[handle] ?? 0) + 1
            return handle
        }
    }

    func get(handle: UniFFICallbackHandle) -> T? {
        lock.withLock {
            leftMap[handle]
        }
    }

    func delete(handle: UniFFICallbackHandle) {
        remove(handle: handle)
    }

    @discardableResult
    func remove(handle: UniFFICallbackHandle) -> T? {
        lock.withLock {
            defer { counter[handle] = (counter[handle] ?? 1) - 1 }
            guard counter[handle] == 1 else { return leftMap[handle] }
            let obj = leftMap.removeValue(forKey: handle)
            if let obj = obj {
                rightMap.removeValue(forKey: ObjectIdentifier(obj as AnyObject))
            }
            return obj
        }
    }
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Declaration and FfiConverters for KeyProvider Callback Interface

fileprivate let uniffiCallbackInterfaceKeyProvider : ForeignCallback =
    { (handle: UniFFICallbackHandle, method: Int32, argsData: UnsafePointer<UInt8>, argsLen: Int32, out_buf: UnsafeMutablePointer<RustBuffer>) -> Int32 in
    

    func invokeSecretKey(_ swiftCallbackInterface: KeyProvider, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
        func makeCall() throws -> Int32 {
            let result =  try swiftCallbackInterface.secretKey(
                    )
            var writer = [UInt8]()
            FfiConverterSequenceUInt8.write(result, into: &writer)
            out_buf.pointee = RustBuffer(bytes: writer)
            return UNIFFI_CALLBACK_SUCCESS
        }
        do {
            return try makeCall()
        } catch let error as PubkyError {
            out_buf.pointee = FfiConverterTypePubkyError.lower(error)
            return UNIFFI_CALLBACK_ERROR
        }
    }


    switch method {
        case IDX_CALLBACK_FREE:
            FfiConverterTypeKeyProvider.handleMap.remove(handle: handle)
            // Successful return
            // See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs`
            return UNIFFI_CALLBACK_SUCCESS
        case 1:
            guard let cb = FfiConverterTypeKeyProvider.handleMap.get(handle: handle) else {
                out_buf.pointee = FfiConverterString.lower("No callback in handlemap; this is a Uniffi bug")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeSecretKey(cb, argsData, argsLen, out_buf)
            } catch let error {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
        
        // This should never happen, because an out of bounds method index won't
        // ever be used. Once we can catch errors, we should return an InternalError.
        // https://github.com/mozilla/uniffi-rs/issues/351
        default:
            // An unexpected error happened.
            // See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs`
            return UNIFFI_CALLBACK_UNEXPECTED_ERROR
    }
}

private func uniffiCallbackInitKeyProvider() {
    uniffi_pubky_fn_init_callback_keyprovider(uniffiCallbackInterfaceKeyProvider)
}

public struct FfiConverterTypeKeyProvider: FfiConverter {
    fileprivate static var handleMap = UniFFICallbackHandleMap<KeyProvider>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = KeyProvider

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> KeyProvider {
        return KeyProviderImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: KeyProvider) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KeyProvider {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: KeyProvider, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeKeyProvider_lift(_ pointer: UnsafeMutableRawPointer) throws -> KeyProvider {
    return try FfiConverterTypeKeyProvider.lift(pointer)
}

public func FfiConverterTypeKeyProvider_lower(_ value: KeyProvider) -> UnsafeMutableRawPointer {
    return FfiConverterTypeKeyProvider.lower(value)
}




public protocol PubkySessionProtocol : AnyObject {
    
    func info()  -> SessionInfo
    
    func signout() throws 
    
    func storage()  -> SessionStorage
    
}

public class PubkySession:
    PubkySessionProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_fn_clone_pubkysession(self.pointer, $0) }
    }

    deinit {
        try! rustCall { uniffi_pubky_fn_free_pubkysession(pointer, $0) }
    }

    

    
    
    public func info()  -> SessionInfo {
        return try!  FfiConverterTypeSessionInfo.lift(
            try! 
    rustCall() {
    
    uniffi_pubky_fn_method_pubkysession_info(self.uniffiClonePointer(), $0
    )
}
        )
    }
    public func signout() throws  {
        try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_pubkysession_signout(self.uniffiClonePointer(), $0
    )
}
    }
    public func storage()  -> SessionStorage {
        return try!  FfiConverterTypeSessionStorage.lift(
            try! 
    rustCall() {
    
    uniffi_pubky_fn_method_pubkysession_storage(self.uniffiClonePointer(), $0
    )
}
        )
    }

}

public struct FfiConverterTypePubkySession: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PubkySession

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PubkySession {
        return PubkySession(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PubkySession) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PubkySession {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PubkySession, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypePubkySession_lift(_ pointer: UnsafeMutableRawPointer) throws -> PubkySession {
    return try FfiConverterTypePubkySession.lift(pointer)
}

public func FfiConverterTypePubkySession_lower(_ value: PubkySession) -> UnsafeMutableRawPointer {
    return FfiConverterTypePubkySession.lower(value)
}




public protocol PublicStorageProtocol : AnyObject {
    
    func get(uri: String) throws  -> [UInt8]
    
    func list(uri: String) throws  -> [ListItem]
    
}

public class PublicStorage:
    PublicStorageProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_fn_clone_publicstorage(self.pointer, $0) }
    }

    deinit {
        try! rustCall { uniffi_pubky_fn_free_publicstorage(pointer, $0) }
    }

    

    
    
    public func get(uri: String) throws  -> [UInt8] {
        return try  FfiConverterSequenceUInt8.lift(
            try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_publicstorage_get(self.uniffiClonePointer(), 
        FfiConverterString.lower(uri),$0
    )
}
        )
    }
    public func list(uri: String) throws  -> [ListItem] {
        return try  FfiConverterSequenceTypeListItem.lift(
            try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_publicstorage_list(self.uniffiClonePointer(), 
        FfiConverterString.lower(uri),$0
    )
}
        )
    }

}

public struct FfiConverterTypePublicStorage: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PublicStorage

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PublicStorage {
        return PublicStorage(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PublicStorage) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PublicStorage {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PublicStorage, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypePublicStorage_lift(_ pointer: UnsafeMutableRawPointer) throws -> PublicStorage {
    return try FfiConverterTypePublicStorage.lift(pointer)
}

public func FfiConverterTypePublicStorage_lower(_ value: PublicStorage) -> UnsafeMutableRawPointer {
    return FfiConverterTypePublicStorage.lower(value)
}




public protocol SdkProtocol : AnyObject {
    
    func awaitApproval(requestId: String) throws  -> PubkySession
    
    func publicStorage()  -> PublicStorage
    
    func signin(keyProvider: KeyProvider, homeserver: String) throws  -> PubkySession
    
    func signup(keyProvider: KeyProvider, homeserver: String, options: SignupOptions?) throws  -> PubkySession
    
    func startAuthFlow(capabilities: [String]) throws  -> AuthFlowInfo
    
}

public class Sdk:
    SdkProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_fn_clone_sdk(self.pointer, $0) }
    }
    public convenience init()  {
        self.init(unsafeFromRawPointer: try! rustCall() {
    uniffi_pubky_fn_constructor_sdk_new($0)
})
    }

    deinit {
        try! rustCall { uniffi_pubky_fn_free_sdk(pointer, $0) }
    }

    

    
    
    public func awaitApproval(requestId: String) throws  -> PubkySession {
        return try  FfiConverterTypePubkySession.lift(
            try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_sdk_await_approval(self.uniffiClonePointer(), 
        FfiConverterString.lower(requestId),$0
    )
}
        )
    }
    public func publicStorage()  -> PublicStorage {
        return try!  FfiConverterTypePublicStorage.lift(
            try! 
    rustCall() {
    
    uniffi_pubky_fn_method_sdk_public_storage(self.uniffiClonePointer(), $0
    )
}
        )
    }
    public func signin(keyProvider: KeyProvider, homeserver: String) throws  -> PubkySession {
        return try  FfiConverterTypePubkySession.lift(
            try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_sdk_signin(self.uniffiClonePointer(), 
        FfiConverterTypeKeyProvider.lower(keyProvider),
        FfiConverterString.lower(homeserver),$0
    )
}
        )
    }
    public func signup(keyProvider: KeyProvider, homeserver: String, options: SignupOptions?) throws  -> PubkySession {
        return try  FfiConverterTypePubkySession.lift(
            try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_sdk_signup(self.uniffiClonePointer(), 
        FfiConverterTypeKeyProvider.lower(keyProvider),
        FfiConverterString.lower(homeserver),
        FfiConverterOptionTypeSignupOptions.lower(options),$0
    )
}
        )
    }
    public func startAuthFlow(capabilities: [String]) throws  -> AuthFlowInfo {
        return try  FfiConverterTypeAuthFlowInfo.lift(
            try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_sdk_start_auth_flow(self.uniffiClonePointer(), 
        FfiConverterSequenceString.lower(capabilities),$0
    )
}
        )
    }

}

public struct FfiConverterTypeSdk: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Sdk

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Sdk {
        return Sdk(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Sdk) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Sdk {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Sdk, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeSdk_lift(_ pointer: UnsafeMutableRawPointer) throws -> Sdk {
    return try FfiConverterTypeSdk.lift(pointer)
}

public func FfiConverterTypeSdk_lower(_ value: Sdk) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSdk.lower(value)
}




public protocol SessionStorageProtocol : AnyObject {
    
    func delete(path: String) throws 
    
    func get(path: String) throws  -> [UInt8]
    
    func list(path: String) throws  -> [ListItem]
    
    func put(path: String, content: [UInt8]) throws 
    
}

public class SessionStorage:
    SessionStorageProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_fn_clone_sessionstorage(self.pointer, $0) }
    }

    deinit {
        try! rustCall { uniffi_pubky_fn_free_sessionstorage(pointer, $0) }
    }

    

    
    
    public func delete(path: String) throws  {
        try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_sessionstorage_delete(self.uniffiClonePointer(), 
        FfiConverterString.lower(path),$0
    )
}
    }
    public func get(path: String) throws  -> [UInt8] {
        return try  FfiConverterSequenceUInt8.lift(
            try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_sessionstorage_get(self.uniffiClonePointer(), 
        FfiConverterString.lower(path),$0
    )
}
        )
    }
    public func list(path: String) throws  -> [ListItem] {
        return try  FfiConverterSequenceTypeListItem.lift(
            try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_sessionstorage_list(self.uniffiClonePointer(), 
        FfiConverterString.lower(path),$0
    )
}
        )
    }
    public func put(path: String, content: [UInt8]) throws  {
        try 
    rustCallWithError(FfiConverterTypePubkyError.lift) {
    uniffi_pubky_fn_method_sessionstorage_put(self.uniffiClonePointer(), 
        FfiConverterString.lower(path),
        FfiConverterSequenceUInt8.lower(content),$0
    )
}
    }

}

public struct FfiConverterTypeSessionStorage: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SessionStorage

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SessionStorage {
        return SessionStorage(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SessionStorage) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionStorage {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SessionStorage, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeSessionStorage_lift(_ pointer: UnsafeMutableRawPointer) throws -> SessionStorage {
    return try FfiConverterTypeSessionStorage.lift(pointer)
}

public func FfiConverterTypeSessionStorage_lower(_ value: SessionStorage) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSessionStorage.lower(value)
}


public struct AuthFlowInfo {
    public var authorizationUrl: String
    public var requestId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        authorizationUrl: String, 
        requestId: String) {
        self.authorizationUrl = authorizationUrl
        self.requestId = requestId
    }
}


extension AuthFlowInfo: Equatable, Hashable {
    public static func ==(lhs: AuthFlowInfo, rhs: AuthFlowInfo) -> Bool {
        if lhs.authorizationUrl != rhs.authorizationUrl {
            return false
        }
        if lhs.requestId != rhs.requestId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(authorizationUrl)
        hasher.combine(requestId)
    }
}


public struct FfiConverterTypeAuthFlowInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthFlowInfo {
        return
            try AuthFlowInfo(
                authorizationUrl: FfiConverterString.read(from: &buf), 
                requestId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AuthFlowInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.authorizationUrl, into: &buf)
        FfiConverterString.write(value.requestId, into: &buf)
    }
}


public func FfiConverterTypeAuthFlowInfo_lift(_ buf: RustBuffer) throws -> AuthFlowInfo {
    return try FfiConverterTypeAuthFlowInfo.lift(buf)
}

public func FfiConverterTypeAuthFlowInfo_lower(_ value: AuthFlowInfo) -> RustBuffer {
    return FfiConverterTypeAuthFlowInfo.lower(value)
}


public struct ListItem {
    public var name: String
    public var isDirectory: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        name: String, 
        isDirectory: Bool) {
        self.name = name
        self.isDirectory = isDirectory
    }
}


extension ListItem: Equatable, Hashable {
    public static func ==(lhs: ListItem, rhs: ListItem) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.isDirectory != rhs.isDirectory {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(isDirectory)
    }
}


public struct FfiConverterTypeListItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ListItem {
        return
            try ListItem(
                name: FfiConverterString.read(from: &buf), 
                isDirectory: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ListItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterBool.write(value.isDirectory, into: &buf)
    }
}


public func FfiConverterTypeListItem_lift(_ buf: RustBuffer) throws -> ListItem {
    return try FfiConverterTypeListItem.lift(buf)
}

public func FfiConverterTypeListItem_lower(_ value: ListItem) -> RustBuffer {
    return FfiConverterTypeListItem.lower(value)
}


public struct SessionInfo {
    public var pubkey: String
    public var sessionSecret: String?
    public var capabilities: [String]
    public var createdAt: UInt64
    public var expiresAt: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        pubkey: String, 
        sessionSecret: String?, 
        capabilities: [String], 
        createdAt: UInt64, 
        expiresAt: UInt64?) {
        self.pubkey = pubkey
        self.sessionSecret = sessionSecret
        self.capabilities = capabilities
        self.createdAt = createdAt
        self.expiresAt = expiresAt
    }
}


extension SessionInfo: Equatable, Hashable {
    public static func ==(lhs: SessionInfo, rhs: SessionInfo) -> Bool {
        if lhs.pubkey != rhs.pubkey {
            return false
        }
        if lhs.sessionSecret != rhs.sessionSecret {
            return false
        }
        if lhs.capabilities != rhs.capabilities {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.expiresAt != rhs.expiresAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pubkey)
        hasher.combine(sessionSecret)
        hasher.combine(capabilities)
        hasher.combine(createdAt)
        hasher.combine(expiresAt)
    }
}


public struct FfiConverterTypeSessionInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionInfo {
        return
            try SessionInfo(
                pubkey: FfiConverterString.read(from: &buf), 
                sessionSecret: FfiConverterOptionString.read(from: &buf), 
                capabilities: FfiConverterSequenceString.read(from: &buf), 
                createdAt: FfiConverterUInt64.read(from: &buf), 
                expiresAt: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: SessionInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkey, into: &buf)
        FfiConverterOptionString.write(value.sessionSecret, into: &buf)
        FfiConverterSequenceString.write(value.capabilities, into: &buf)
        FfiConverterUInt64.write(value.createdAt, into: &buf)
        FfiConverterOptionUInt64.write(value.expiresAt, into: &buf)
    }
}


public func FfiConverterTypeSessionInfo_lift(_ buf: RustBuffer) throws -> SessionInfo {
    return try FfiConverterTypeSessionInfo.lift(buf)
}

public func FfiConverterTypeSessionInfo_lower(_ value: SessionInfo) -> RustBuffer {
    return FfiConverterTypeSessionInfo.lower(value)
}


public struct SignupOptions {
    public var capabilities: [String]?
    public var signupToken: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        capabilities: [String]?, 
        signupToken: UInt64?) {
        self.capabilities = capabilities
        self.signupToken = signupToken
    }
}


extension SignupOptions: Equatable, Hashable {
    public static func ==(lhs: SignupOptions, rhs: SignupOptions) -> Bool {
        if lhs.capabilities != rhs.capabilities {
            return false
        }
        if lhs.signupToken != rhs.signupToken {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(capabilities)
        hasher.combine(signupToken)
    }
}


public struct FfiConverterTypeSignupOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignupOptions {
        return
            try SignupOptions(
                capabilities: FfiConverterOptionSequenceString.read(from: &buf), 
                signupToken: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: SignupOptions, into buf: inout [UInt8]) {
        FfiConverterOptionSequenceString.write(value.capabilities, into: &buf)
        FfiConverterOptionUInt64.write(value.signupToken, into: &buf)
    }
}


public func FfiConverterTypeSignupOptions_lift(_ buf: RustBuffer) throws -> SignupOptions {
    return try FfiConverterTypeSignupOptions.lift(buf)
}

public func FfiConverterTypeSignupOptions_lower(_ value: SignupOptions) -> RustBuffer {
    return FfiConverterTypeSignupOptions.lower(value)
}


public enum PubkyError {

    
    
    case Auth(message: String)
    
    case Request(message: String)
    
    case Build(message: String)
    
    case InvalidInput(message: String)
    
    case Network(message: String)
    
    case Unknown(message: String)
    

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypePubkyError.lift(error)
    }
}


public struct FfiConverterTypePubkyError: FfiConverterRustBuffer {
    typealias SwiftType = PubkyError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PubkyError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Auth(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Request(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Build(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .Network(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Unknown(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PubkyError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Auth(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Request(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Build(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .InvalidInput(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .Network(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Unknown(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


extension PubkyError: Equatable, Hashable {}

extension PubkyError: Error { }

fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionTypeSignupOptions: FfiConverterRustBuffer {
    typealias SwiftType = SignupOptions?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSignupOptions.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSignupOptions.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeListItem: FfiConverterRustBuffer {
    typealias SwiftType = [ListItem]

    public static func write(_ value: [ListItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeListItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ListItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [ListItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeListItem.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 25
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pubky_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pubky_checksum_method_keyprovider_secret_key() != 27423) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_pubkysession_info() != 16134) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_pubkysession_signout() != 31266) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_pubkysession_storage() != 63613) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_publicstorage_get() != 32316) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_publicstorage_list() != 4306) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_sdk_await_approval() != 35272) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_sdk_public_storage() != 16815) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_sdk_signin() != 31462) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_sdk_signup() != 51229) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_sdk_start_auth_flow() != 2146) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_sessionstorage_delete() != 52688) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_sessionstorage_get() != 49563) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_sessionstorage_list() != 33623) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_method_sessionstorage_put() != 46158) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_checksum_constructor_sdk_new() != 55923) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitKeyProvider()
    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}