// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, const uint8_t *_Nonnull, int32_t, RustBuffer *_Nonnull);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Continuation callback for UniFFI Futures
typedef void (*UniFfiRustFutureContinuation)(void * _Nonnull, int8_t);

// Scaffolding functions
void*_Nonnull uniffi_paykit_mobile_fn_clone_authenticatedtransportffi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_free_authenticatedtransportffi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_authenticatedtransportffi_from_callback(uint64_t callback, RustBuffer owner_pubkey, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_authenticatedtransportffi_from_session_json(RustBuffer session_json, RustBuffer owner_pubkey, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_authenticatedtransportffi_new_mock(RustBuffer owner_pubkey, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_authenticatedtransportffi_delete(void*_Nonnull ptr, RustBuffer path, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_authenticatedtransportffi_get(void*_Nonnull ptr, RustBuffer path, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_paykit_mobile_fn_method_authenticatedtransportffi_is_mock(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_authenticatedtransportffi_list(void*_Nonnull ptr, RustBuffer prefix, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_authenticatedtransportffi_owner_pubkey(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_authenticatedtransportffi_put(void*_Nonnull ptr, RustBuffer path, RustBuffer content, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_clone_contactcacheffi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_free_contactcacheffi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_contactcacheffi_new(RustCallStatus *_Nonnull out_status
    
);
void uniffi_paykit_mobile_fn_method_contactcacheffi_add(void*_Nonnull ptr, RustBuffer pubkey, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_contactcacheffi_add_with_name(void*_Nonnull ptr, RustBuffer pubkey, RustBuffer name, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_contactcacheffi_clear(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_paykit_mobile_fn_method_contactcacheffi_contains(void*_Nonnull ptr, RustBuffer pubkey, RustCallStatus *_Nonnull out_status
);
uint32_t uniffi_paykit_mobile_fn_method_contactcacheffi_count(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_contactcacheffi_get(void*_Nonnull ptr, RustBuffer pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_contactcacheffi_get_all(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_contactcacheffi_remove(void*_Nonnull ptr, RustBuffer pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_contactcacheffi_sync(void*_Nonnull ptr, RustBuffer remote_pubkeys, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_clone_directoryoperationsasync(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_free_directoryoperationsasync(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_directoryoperationsasync_new(RustCallStatus *_Nonnull out_status
    
);
void uniffi_paykit_mobile_fn_method_directoryoperationsasync_add_contact(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer contact_pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_directoryoperationsasync_fetch_known_contacts(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer owner_pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_directoryoperationsasync_fetch_payment_endpoint(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer owner_pubkey, RustBuffer method_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_directoryoperationsasync_fetch_supported_payments(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer owner_pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_directoryoperationsasync_list_contacts(void*_Nonnull ptr, void*_Nonnull transport, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_directoryoperationsasync_publish_payment_endpoint(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer method_id, RustBuffer endpoint_data, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_directoryoperationsasync_remove_contact(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer contact_pubkey, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_directoryoperationsasync_remove_payment_endpoint(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer method_id, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_clone_executorasyncbridge(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_free_executorasyncbridge(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_executorasyncbridge_new(RustCallStatus *_Nonnull out_status
    
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_executorasyncbridge_with_timeout(uint64_t timeout_ms, RustCallStatus *_Nonnull out_status
);
uint64_t uniffi_paykit_mobile_fn_method_executorasyncbridge_default_timeout_ms(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_clone_paykitclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_free_paykitclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_paykitclient_new(RustCallStatus *_Nonnull out_status
    
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_paykitclient_new_with_network(RustBuffer bitcoin_network, RustBuffer lightning_network, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_paykitclient_add_contact(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer contact_pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_bitcoin_network(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_calculate_proration(void*_Nonnull ptr, int64_t current_amount_sats, int64_t new_amount_sats, int64_t period_start, int64_t period_end, int64_t change_date, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_check_health(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_create_noise_error_message(void*_Nonnull ptr, RustBuffer code, RustBuffer message, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_create_payment_request(void*_Nonnull ptr, RustBuffer from_pubkey, RustBuffer to_pubkey, int64_t amount_sats, RustBuffer currency, RustBuffer method_id, RustBuffer description, RustBuffer expires_in_secs, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_create_receipt(void*_Nonnull ptr, RustBuffer payer, RustBuffer payee, RustBuffer method_id, RustBuffer amount, RustBuffer currency, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_create_receipt_confirmation_message(void*_Nonnull ptr, RustBuffer receipt_id, RustBuffer payer_pubkey, RustBuffer payee_pubkey, RustBuffer method_id, RustBuffer amount, RustBuffer currency, RustBuffer signature, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_create_receipt_request_message(void*_Nonnull ptr, RustBuffer receipt_id, RustBuffer payer_pubkey, RustBuffer payee_pubkey, RustBuffer method_id, RustBuffer amount, RustBuffer currency, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_create_subscription(void*_Nonnull ptr, RustBuffer subscriber, RustBuffer provider, RustBuffer terms, RustCallStatus *_Nonnull out_status
);
uint32_t uniffi_paykit_mobile_fn_method_paykitclient_days_remaining_in_period(void*_Nonnull ptr, int64_t period_end, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_discover_noise_endpoint(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer recipient_pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_execute_payment(void*_Nonnull ptr, RustBuffer method_id, RustBuffer endpoint, uint64_t amount_sats, RustBuffer metadata_json, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_extract_key_from_qr(void*_Nonnull ptr, RustBuffer scanned_data, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_extract_method_from_qr(void*_Nonnull ptr, RustBuffer scanned_data, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_fetch_known_contacts(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer owner_pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_fetch_payment_endpoint(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer owner_pubkey, RustBuffer method_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_fetch_supported_payments(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer owner_pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_generate_payment_proof(void*_Nonnull ptr, RustBuffer method_id, RustBuffer execution_data_json, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_get_health_status(void*_Nonnull ptr, RustBuffer method_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_get_in_progress_payments(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_get_payment_status(void*_Nonnull ptr, RustBuffer receipt_id, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_paykit_mobile_fn_method_paykitclient_has_bitcoin_executor(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_paykit_mobile_fn_method_paykitclient_has_lightning_executor(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_paykit_mobile_fn_method_paykitclient_is_method_usable(void*_Nonnull ptr, RustBuffer method_id, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_paykit_mobile_fn_method_paykitclient_is_paykit_qr(void*_Nonnull ptr, RustBuffer scanned_data, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_lightning_network(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_list_contacts(void*_Nonnull ptr, void*_Nonnull transport, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_list_methods(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_parse_noise_payment_message(void*_Nonnull ptr, RustBuffer json, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_parse_receipt_metadata(void*_Nonnull ptr, RustBuffer metadata_json, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_parse_scanned_qr(void*_Nonnull ptr, RustBuffer scanned_data, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_paykitclient_publish_noise_endpoint(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer host, uint16_t port, RustBuffer noise_pubkey, RustBuffer metadata, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_paykitclient_publish_payment_endpoint(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer method_id, RustBuffer endpoint_data, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_paykitclient_register_bitcoin_executor(void*_Nonnull ptr, uint64_t executor, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_paykitclient_register_lightning_executor(void*_Nonnull ptr, uint64_t executor, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_paykitclient_remove_contact(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer contact_pubkey, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_paykitclient_remove_noise_endpoint(void*_Nonnull ptr, void*_Nonnull transport, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_paykitclient_remove_payment_endpoint_from_directory(void*_Nonnull ptr, void*_Nonnull transport, RustBuffer method_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitclient_select_method(void*_Nonnull ptr, RustBuffer supported_methods, uint64_t amount_sats, RustBuffer preferences, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_paykit_mobile_fn_method_paykitclient_validate_endpoint(void*_Nonnull ptr, RustBuffer method_id, RustBuffer endpoint, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_clone_paykitinteractivemanagerffi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_free_paykitinteractivemanagerffi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_paykitinteractivemanagerffi_new(void*_Nonnull store, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitinteractivemanagerffi_create_endpoint_offer(void*_Nonnull ptr, RustBuffer method_id, RustBuffer endpoint, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitinteractivemanagerffi_create_payment_request(void*_Nonnull ptr, RustBuffer payer, RustBuffer payee, RustBuffer method_id, RustBuffer amount, RustBuffer currency, RustBuffer metadata_json, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitinteractivemanagerffi_get_private_endpoint(void*_Nonnull ptr, RustBuffer peer, RustBuffer method_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitinteractivemanagerffi_get_receipt(void*_Nonnull ptr, RustBuffer receipt_id, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_method_paykitinteractivemanagerffi_get_store(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitinteractivemanagerffi_handle_message(void*_Nonnull ptr, RustBuffer message_json, RustBuffer peer_pubkey, RustBuffer my_pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitinteractivemanagerffi_handle_payment_response(void*_Nonnull ptr, RustBuffer response_json, RustBuffer original_receipt_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitinteractivemanagerffi_list_private_endpoints(void*_Nonnull ptr, RustBuffer peer, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitinteractivemanagerffi_list_receipts(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_paykitinteractivemanagerffi_set_generator(void*_Nonnull ptr, uint64_t generator, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_clone_paykitmessagebuilder(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_free_paykitmessagebuilder(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_paykitmessagebuilder_new(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitmessagebuilder_create_ack(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitmessagebuilder_create_endpoint_offer(void*_Nonnull ptr, RustBuffer method_id, RustBuffer endpoint, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitmessagebuilder_create_error(void*_Nonnull ptr, RustBuffer code, RustBuffer message, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitmessagebuilder_create_receipt_confirm(void*_Nonnull ptr, RustBuffer receipt, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitmessagebuilder_create_receipt_request(void*_Nonnull ptr, RustBuffer request, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitmessagebuilder_get_message_type(void*_Nonnull ptr, RustBuffer message_json, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_paykitmessagebuilder_parse_message(void*_Nonnull ptr, RustBuffer message_json, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_clone_receiptstore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_free_receiptstore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_receiptstore_new(RustCallStatus *_Nonnull out_status
    
);
void uniffi_paykit_mobile_fn_method_receiptstore_clear(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_receiptstore_delete_receipt(void*_Nonnull ptr, RustBuffer receipt_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_receiptstore_export_receipts_json(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_receiptstore_get_private_endpoint(void*_Nonnull ptr, RustBuffer peer, RustBuffer method_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_receiptstore_get_receipt(void*_Nonnull ptr, RustBuffer receipt_id, RustCallStatus *_Nonnull out_status
);
uint32_t uniffi_paykit_mobile_fn_method_receiptstore_import_receipts_json(void*_Nonnull ptr, RustBuffer json, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_receiptstore_list_private_endpoints(void*_Nonnull ptr, RustBuffer peer, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_receiptstore_list_receipts(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_receiptstore_save_private_endpoint(void*_Nonnull ptr, RustBuffer peer, RustBuffer offer, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_method_receiptstore_save_receipt(void*_Nonnull ptr, RustBuffer receipt, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_clone_unauthenticatedtransportffi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_free_unauthenticatedtransportffi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_unauthenticatedtransportffi_from_authenticated(void*_Nonnull auth, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_unauthenticatedtransportffi_from_callback(uint64_t callback, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_unauthenticatedtransportffi_from_config_json(RustBuffer config_json, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_constructor_unauthenticatedtransportffi_new_mock(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_paykit_mobile_fn_method_unauthenticatedtransportffi_get(void*_Nonnull ptr, RustBuffer owner_pubkey, RustBuffer path, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_paykit_mobile_fn_method_unauthenticatedtransportffi_is_mock(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_method_unauthenticatedtransportffi_list(void*_Nonnull ptr, RustBuffer owner_pubkey, RustBuffer prefix, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_init_callback_bitcoinexecutorffi(ForeignCallback _Nonnull handle
);
void uniffi_paykit_mobile_fn_init_callback_lightningexecutorffi(ForeignCallback _Nonnull handle
);
void uniffi_paykit_mobile_fn_init_callback_pubkyauthenticatedstoragecallback(ForeignCallback _Nonnull handle
);
void uniffi_paykit_mobile_fn_init_callback_pubkyunauthenticatedstoragecallback(ForeignCallback _Nonnull handle
);
void uniffi_paykit_mobile_fn_init_callback_receiptgeneratorcallback(ForeignCallback _Nonnull handle
);
void*_Nonnull uniffi_paykit_mobile_fn_func_create_contact_cache(RustCallStatus *_Nonnull out_status
    
);
void*_Nonnull uniffi_paykit_mobile_fn_func_create_directory_operations_async(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_paykit_mobile_fn_func_create_error_message(RustBuffer code, RustBuffer message, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_func_create_executor_async_bridge(RustCallStatus *_Nonnull out_status
    
);
void*_Nonnull uniffi_paykit_mobile_fn_func_create_executor_async_bridge_with_timeout(uint64_t timeout_ms, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_func_create_interactive_manager(void*_Nonnull store, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_func_create_message_builder(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_paykit_mobile_fn_func_create_noise_server_config(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_paykit_mobile_fn_func_create_noise_server_config_with_port(uint16_t port, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_func_create_paykit_client(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_paykit_mobile_fn_func_create_private_endpoint_offer_message(RustBuffer method_id, RustBuffer endpoint, RustBuffer expires_in_secs, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_func_create_receipt_confirmation_message(RustBuffer receipt_id, RustBuffer payer_pubkey, RustBuffer payee_pubkey, RustBuffer method_id, RustBuffer amount, RustBuffer currency, RustBuffer signature, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_func_create_receipt_request_message(RustBuffer receipt_id, RustBuffer payer_pubkey, RustBuffer payee_pubkey, RustBuffer method_id, RustBuffer amount, RustBuffer currency, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_paykit_mobile_fn_func_create_receipt_store(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_paykit_mobile_fn_func_derive_x25519_keypair(RustBuffer ed25519_secret_hex, RustBuffer device_id, uint32_t epoch, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_func_discover_noise_endpoint(void*_Nonnull transport, RustBuffer recipient_pubkey, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_func_ed25519_keypair_from_secret(RustBuffer secret_key_hex, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_func_export_keypair_to_backup(RustBuffer secret_key_hex, RustBuffer password, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_func_format_public_key_z32(RustBuffer public_key_hex, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_func_generate_device_id(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_paykit_mobile_fn_func_generate_ed25519_keypair(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_paykit_mobile_fn_func_get_version(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_paykit_mobile_fn_func_import_keypair_from_backup(RustBuffer backup, RustBuffer password, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_func_parse_payment_message(RustBuffer json, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_func_parse_public_key_z32(RustBuffer public_key_z32, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_func_publish_noise_endpoint(void*_Nonnull transport, RustBuffer host, uint16_t port, RustBuffer noise_pubkey, RustBuffer metadata, RustCallStatus *_Nonnull out_status
);
void uniffi_paykit_mobile_fn_func_remove_noise_endpoint(void*_Nonnull transport, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_paykit_mobile_fn_func_sign_message(RustBuffer secret_key_hex, RustBuffer message, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_paykit_mobile_fn_func_verify_signature(RustBuffer public_key_hex, RustBuffer message, RustBuffer signature_hex, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_paykit_mobile_rustbuffer_alloc(int32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_paykit_mobile_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_paykit_mobile_rustbuffer_reserve(RustBuffer buf, int32_t additional, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_u8(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_u8(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_u8(void* _Nonnull handle
);
uint8_t ffi_paykit_mobile_rust_future_complete_u8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_i8(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_i8(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_i8(void* _Nonnull handle
);
int8_t ffi_paykit_mobile_rust_future_complete_i8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_u16(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_u16(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_u16(void* _Nonnull handle
);
uint16_t ffi_paykit_mobile_rust_future_complete_u16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_i16(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_i16(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_i16(void* _Nonnull handle
);
int16_t ffi_paykit_mobile_rust_future_complete_i16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_u32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_u32(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_u32(void* _Nonnull handle
);
uint32_t ffi_paykit_mobile_rust_future_complete_u32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_i32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_i32(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_i32(void* _Nonnull handle
);
int32_t ffi_paykit_mobile_rust_future_complete_i32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_u64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_u64(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_u64(void* _Nonnull handle
);
uint64_t ffi_paykit_mobile_rust_future_complete_u64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_i64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_i64(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_i64(void* _Nonnull handle
);
int64_t ffi_paykit_mobile_rust_future_complete_i64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_f32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_f32(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_f32(void* _Nonnull handle
);
float ffi_paykit_mobile_rust_future_complete_f32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_f64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_f64(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_f64(void* _Nonnull handle
);
double ffi_paykit_mobile_rust_future_complete_f64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_pointer(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_pointer(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_pointer(void* _Nonnull handle
);
void*_Nonnull ffi_paykit_mobile_rust_future_complete_pointer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_rust_buffer(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_rust_buffer(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_rust_buffer(void* _Nonnull handle
);
RustBuffer ffi_paykit_mobile_rust_future_complete_rust_buffer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_paykit_mobile_rust_future_poll_void(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_paykit_mobile_rust_future_cancel_void(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_free_void(void* _Nonnull handle
);
void ffi_paykit_mobile_rust_future_complete_void(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
uint16_t uniffi_paykit_mobile_checksum_func_create_contact_cache(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_directory_operations_async(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_error_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_executor_async_bridge(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_executor_async_bridge_with_timeout(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_interactive_manager(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_message_builder(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_noise_server_config(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_noise_server_config_with_port(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_paykit_client(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_private_endpoint_offer_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_receipt_confirmation_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_receipt_request_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_create_receipt_store(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_derive_x25519_keypair(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_discover_noise_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_ed25519_keypair_from_secret(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_export_keypair_to_backup(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_format_public_key_z32(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_generate_device_id(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_generate_ed25519_keypair(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_get_version(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_import_keypair_from_backup(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_parse_payment_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_parse_public_key_z32(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_publish_noise_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_remove_noise_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_sign_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_func_verify_signature(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_authenticatedtransportffi_delete(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_authenticatedtransportffi_get(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_authenticatedtransportffi_is_mock(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_authenticatedtransportffi_list(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_authenticatedtransportffi_owner_pubkey(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_authenticatedtransportffi_put(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_contactcacheffi_add(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_contactcacheffi_add_with_name(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_contactcacheffi_clear(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_contactcacheffi_contains(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_contactcacheffi_count(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_contactcacheffi_get(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_contactcacheffi_get_all(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_contactcacheffi_remove(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_contactcacheffi_sync(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_directoryoperationsasync_add_contact(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_directoryoperationsasync_fetch_known_contacts(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_directoryoperationsasync_fetch_payment_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_directoryoperationsasync_fetch_supported_payments(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_directoryoperationsasync_list_contacts(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_directoryoperationsasync_publish_payment_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_directoryoperationsasync_remove_contact(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_directoryoperationsasync_remove_payment_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_executorasyncbridge_default_timeout_ms(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_add_contact(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_bitcoin_network(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_calculate_proration(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_check_health(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_create_noise_error_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_create_payment_request(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_create_receipt(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_create_receipt_confirmation_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_create_receipt_request_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_create_subscription(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_days_remaining_in_period(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_discover_noise_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_execute_payment(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_extract_key_from_qr(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_extract_method_from_qr(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_fetch_known_contacts(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_fetch_payment_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_fetch_supported_payments(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_generate_payment_proof(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_get_health_status(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_get_in_progress_payments(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_get_payment_status(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_has_bitcoin_executor(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_has_lightning_executor(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_is_method_usable(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_is_paykit_qr(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_lightning_network(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_list_contacts(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_list_methods(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_parse_noise_payment_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_parse_receipt_metadata(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_parse_scanned_qr(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_publish_noise_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_publish_payment_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_register_bitcoin_executor(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_register_lightning_executor(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_remove_contact(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_remove_noise_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_remove_payment_endpoint_from_directory(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_select_method(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitclient_validate_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitinteractivemanagerffi_create_endpoint_offer(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitinteractivemanagerffi_create_payment_request(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitinteractivemanagerffi_get_private_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitinteractivemanagerffi_get_receipt(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitinteractivemanagerffi_get_store(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitinteractivemanagerffi_handle_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitinteractivemanagerffi_handle_payment_response(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitinteractivemanagerffi_list_private_endpoints(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitinteractivemanagerffi_list_receipts(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitinteractivemanagerffi_set_generator(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitmessagebuilder_create_ack(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitmessagebuilder_create_endpoint_offer(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitmessagebuilder_create_error(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitmessagebuilder_create_receipt_confirm(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitmessagebuilder_create_receipt_request(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitmessagebuilder_get_message_type(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_paykitmessagebuilder_parse_message(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptstore_clear(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptstore_delete_receipt(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptstore_export_receipts_json(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptstore_get_private_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptstore_get_receipt(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptstore_import_receipts_json(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptstore_list_private_endpoints(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptstore_list_receipts(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptstore_save_private_endpoint(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptstore_save_receipt(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_unauthenticatedtransportffi_get(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_unauthenticatedtransportffi_is_mock(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_unauthenticatedtransportffi_list(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_authenticatedtransportffi_from_callback(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_authenticatedtransportffi_from_session_json(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_authenticatedtransportffi_new_mock(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_contactcacheffi_new(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_directoryoperationsasync_new(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_executorasyncbridge_new(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_executorasyncbridge_with_timeout(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_paykitclient_new(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_paykitclient_new_with_network(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_paykitinteractivemanagerffi_new(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_paykitmessagebuilder_new(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_receiptstore_new(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_unauthenticatedtransportffi_from_authenticated(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_unauthenticatedtransportffi_from_callback(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_unauthenticatedtransportffi_from_config_json(void
    
);
uint16_t uniffi_paykit_mobile_checksum_constructor_unauthenticatedtransportffi_new_mock(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_bitcoinexecutorffi_send_to_address(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_bitcoinexecutorffi_estimate_fee(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_bitcoinexecutorffi_get_transaction(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_bitcoinexecutorffi_verify_transaction(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_lightningexecutorffi_pay_invoice(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_lightningexecutorffi_decode_invoice(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_lightningexecutorffi_estimate_fee(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_lightningexecutorffi_get_payment(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_lightningexecutorffi_verify_preimage(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_pubkyauthenticatedstoragecallback_put(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_pubkyauthenticatedstoragecallback_get(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_pubkyauthenticatedstoragecallback_delete(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_pubkyauthenticatedstoragecallback_list(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_pubkyunauthenticatedstoragecallback_get(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_pubkyunauthenticatedstoragecallback_list(void
    
);
uint16_t uniffi_paykit_mobile_checksum_method_receiptgeneratorcallback_generate_receipt(void
    
);
uint32_t ffi_paykit_mobile_uniffi_contract_version(void
    
);

