// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, const uint8_t *_Nonnull, int32_t, RustBuffer *_Nonnull);

// Task defined in Rust that Swift executes
typedef void (*UniFfiRustTaskCallback)(const void * _Nullable, int8_t);

// Callback to execute Rust tasks using a Swift Task
//
// Args:
//   executor: ForeignExecutor lowered into a size_t value
//   delay: Delay in MS
//   task: UniFfiRustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*UniFfiForeignExecutorCallback)(size_t, uint32_t, UniFfiRustTaskCallback _Nullable, const void * _Nullable);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Continuation callback for UniFFI Futures
typedef void (*UniFfiRustFutureContinuation)(void * _Nonnull, int8_t);

// Scaffolding functions
void uniffi_pubkycore_fn_free_eventnotifier(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubkycore_fn_init_callback_eventlistener(ForeignCallback _Nonnull callback_stub, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_auth(RustBuffer url, RustBuffer secret_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_create_recovery_file(RustBuffer secret_key, RustBuffer passphrase, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_decrypt_recovery_file(RustBuffer recovery_file, RustBuffer passphrase, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_delete_file(RustBuffer url, RustBuffer secret_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_generate_mnemonic_phrase(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_pubkycore_fn_func_generate_mnemonic_phrase_and_keypair(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_pubkycore_fn_func_generate_secret_key(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_pubkycore_fn_func_get(RustBuffer url, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_get_homeserver(RustBuffer pubky, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_get_public_key_from_secret_key(RustBuffer secret_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_get_signup_token(RustBuffer homeserver_pubky, RustBuffer admin_password, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_list(RustBuffer url, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_mnemonic_phrase_to_keypair(RustBuffer mnemonic_phrase, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_parse_auth_url(RustBuffer url, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_publish(RustBuffer record_name, RustBuffer record_content, RustBuffer secret_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_publish_https(RustBuffer record_name, RustBuffer target, RustBuffer secret_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_put(RustBuffer url, RustBuffer content, RustBuffer secret_key, RustCallStatus *_Nonnull out_status
);
void uniffi_pubkycore_fn_func_remove_event_listener(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_pubkycore_fn_func_republish_homeserver(RustBuffer secret_key, RustBuffer homeserver, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_resolve(RustBuffer public_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_resolve_https(RustBuffer public_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_revalidate_session(RustBuffer session_secret, RustCallStatus *_Nonnull out_status
);
void uniffi_pubkycore_fn_func_set_event_listener(uint64_t listener, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_sign_in(RustBuffer secret_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_sign_out(RustBuffer session_secret, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_sign_up(RustBuffer secret_key, RustBuffer homeserver, RustBuffer signup_token, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_switch_network(int8_t use_testnet, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubkycore_fn_func_validate_mnemonic_phrase(RustBuffer mnemonic_phrase, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_pubkycore_rustbuffer_alloc(int32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_pubkycore_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_pubkycore_rustbuffer_reserve(RustBuffer buf, int32_t additional, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_continuation_callback_set(UniFfiRustFutureContinuation _Nonnull callback
);
void ffi_pubkycore_rust_future_poll_u8(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_u8(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_u8(void* _Nonnull handle
);
uint8_t ffi_pubkycore_rust_future_complete_u8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_i8(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_i8(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_i8(void* _Nonnull handle
);
int8_t ffi_pubkycore_rust_future_complete_i8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_u16(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_u16(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_u16(void* _Nonnull handle
);
uint16_t ffi_pubkycore_rust_future_complete_u16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_i16(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_i16(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_i16(void* _Nonnull handle
);
int16_t ffi_pubkycore_rust_future_complete_i16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_u32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_u32(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_u32(void* _Nonnull handle
);
uint32_t ffi_pubkycore_rust_future_complete_u32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_i32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_i32(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_i32(void* _Nonnull handle
);
int32_t ffi_pubkycore_rust_future_complete_i32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_u64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_u64(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_u64(void* _Nonnull handle
);
uint64_t ffi_pubkycore_rust_future_complete_u64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_i64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_i64(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_i64(void* _Nonnull handle
);
int64_t ffi_pubkycore_rust_future_complete_i64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_f32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_f32(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_f32(void* _Nonnull handle
);
float ffi_pubkycore_rust_future_complete_f32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_f64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_f64(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_f64(void* _Nonnull handle
);
double ffi_pubkycore_rust_future_complete_f64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_pointer(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_pointer(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_pointer(void* _Nonnull handle
);
void*_Nonnull ffi_pubkycore_rust_future_complete_pointer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_rust_buffer(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_rust_buffer(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_rust_buffer(void* _Nonnull handle
);
RustBuffer ffi_pubkycore_rust_future_complete_rust_buffer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubkycore_rust_future_poll_void(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_pubkycore_rust_future_cancel_void(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_free_void(void* _Nonnull handle
);
void ffi_pubkycore_rust_future_complete_void(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
uint16_t uniffi_pubkycore_checksum_func_auth(void
    
);
uint16_t uniffi_pubkycore_checksum_func_create_recovery_file(void
    
);
uint16_t uniffi_pubkycore_checksum_func_decrypt_recovery_file(void
    
);
uint16_t uniffi_pubkycore_checksum_func_delete_file(void
    
);
uint16_t uniffi_pubkycore_checksum_func_generate_mnemonic_phrase(void
    
);
uint16_t uniffi_pubkycore_checksum_func_generate_mnemonic_phrase_and_keypair(void
    
);
uint16_t uniffi_pubkycore_checksum_func_generate_secret_key(void
    
);
uint16_t uniffi_pubkycore_checksum_func_get(void
    
);
uint16_t uniffi_pubkycore_checksum_func_get_homeserver(void
    
);
uint16_t uniffi_pubkycore_checksum_func_get_public_key_from_secret_key(void
    
);
uint16_t uniffi_pubkycore_checksum_func_get_signup_token(void
    
);
uint16_t uniffi_pubkycore_checksum_func_list(void
    
);
uint16_t uniffi_pubkycore_checksum_func_mnemonic_phrase_to_keypair(void
    
);
uint16_t uniffi_pubkycore_checksum_func_parse_auth_url(void
    
);
uint16_t uniffi_pubkycore_checksum_func_publish(void
    
);
uint16_t uniffi_pubkycore_checksum_func_publish_https(void
    
);
uint16_t uniffi_pubkycore_checksum_func_put(void
    
);
uint16_t uniffi_pubkycore_checksum_func_remove_event_listener(void
    
);
uint16_t uniffi_pubkycore_checksum_func_republish_homeserver(void
    
);
uint16_t uniffi_pubkycore_checksum_func_resolve(void
    
);
uint16_t uniffi_pubkycore_checksum_func_resolve_https(void
    
);
uint16_t uniffi_pubkycore_checksum_func_revalidate_session(void
    
);
uint16_t uniffi_pubkycore_checksum_func_set_event_listener(void
    
);
uint16_t uniffi_pubkycore_checksum_func_sign_in(void
    
);
uint16_t uniffi_pubkycore_checksum_func_sign_out(void
    
);
uint16_t uniffi_pubkycore_checksum_func_sign_up(void
    
);
uint16_t uniffi_pubkycore_checksum_func_switch_network(void
    
);
uint16_t uniffi_pubkycore_checksum_func_validate_mnemonic_phrase(void
    
);
uint16_t uniffi_pubkycore_checksum_method_eventlistener_on_event_occurred(void
    
);
uint32_t ffi_pubkycore_uniffi_contract_version(void
    
);

