// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, const uint8_t *_Nonnull, int32_t, RustBuffer *_Nonnull);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Continuation callback for UniFFI Futures
typedef void (*UniFfiRustFutureContinuation)(void * _Nonnull, int8_t);

// Scaffolding functions
void*_Nonnull uniffi_pubky_noise_fn_clone_ffinoisemanager(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_noise_fn_free_ffinoisemanager(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_noise_fn_constructor_ffinoisemanager_new_client(RustBuffer config, RustBuffer client_seed, RustBuffer client_kid, RustBuffer device_id, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_noise_fn_constructor_ffinoisemanager_new_server(RustBuffer config, RustBuffer server_seed, RustBuffer server_kid, RustBuffer device_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_method_ffinoisemanager_accept_connection(void*_Nonnull ptr, RustBuffer first_msg, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_method_ffinoisemanager_complete_connection(void*_Nonnull ptr, RustBuffer session_id, RustBuffer server_response, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_method_ffinoisemanager_connect_client(void*_Nonnull ptr, RustBuffer server_pk, RustBuffer hint, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_method_ffinoisemanager_decrypt(void*_Nonnull ptr, RustBuffer session_id, RustBuffer ciphertext, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_method_ffinoisemanager_encrypt(void*_Nonnull ptr, RustBuffer session_id, RustBuffer plaintext, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_method_ffinoisemanager_get_status(void*_Nonnull ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_method_ffinoisemanager_initiate_connection(void*_Nonnull ptr, RustBuffer server_pk, RustBuffer hint, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_method_ffinoisemanager_list_sessions(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_noise_fn_method_ffinoisemanager_remove_session(void*_Nonnull ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_noise_fn_method_ffinoisemanager_restore_state(void*_Nonnull ptr, RustBuffer state, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_method_ffinoisemanager_save_state(void*_Nonnull ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_noise_fn_method_ffinoisemanager_set_status(void*_Nonnull ptr, RustBuffer session_id, RustBuffer status, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_func_battery_saver_config(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_pubky_noise_fn_func_default_config(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_pubky_noise_fn_func_derive_device_key(RustBuffer seed, RustBuffer device_id, uint32_t epoch, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_noise_fn_func_performance_config(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_pubky_noise_fn_func_public_key_from_secret(RustBuffer secret, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_pubky_noise_rustbuffer_alloc(int32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_pubky_noise_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_pubky_noise_rustbuffer_reserve(RustBuffer buf, int32_t additional, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_u8(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_u8(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_u8(void* _Nonnull handle
);
uint8_t ffi_pubky_noise_rust_future_complete_u8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_i8(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_i8(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_i8(void* _Nonnull handle
);
int8_t ffi_pubky_noise_rust_future_complete_i8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_u16(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_u16(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_u16(void* _Nonnull handle
);
uint16_t ffi_pubky_noise_rust_future_complete_u16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_i16(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_i16(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_i16(void* _Nonnull handle
);
int16_t ffi_pubky_noise_rust_future_complete_i16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_u32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_u32(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_u32(void* _Nonnull handle
);
uint32_t ffi_pubky_noise_rust_future_complete_u32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_i32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_i32(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_i32(void* _Nonnull handle
);
int32_t ffi_pubky_noise_rust_future_complete_i32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_u64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_u64(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_u64(void* _Nonnull handle
);
uint64_t ffi_pubky_noise_rust_future_complete_u64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_i64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_i64(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_i64(void* _Nonnull handle
);
int64_t ffi_pubky_noise_rust_future_complete_i64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_f32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_f32(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_f32(void* _Nonnull handle
);
float ffi_pubky_noise_rust_future_complete_f32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_f64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_f64(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_f64(void* _Nonnull handle
);
double ffi_pubky_noise_rust_future_complete_f64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_pointer(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_pointer(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_pointer(void* _Nonnull handle
);
void*_Nonnull ffi_pubky_noise_rust_future_complete_pointer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_rust_buffer(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_rust_buffer(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_rust_buffer(void* _Nonnull handle
);
RustBuffer ffi_pubky_noise_rust_future_complete_rust_buffer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_noise_rust_future_poll_void(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_noise_rust_future_cancel_void(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_free_void(void* _Nonnull handle
);
void ffi_pubky_noise_rust_future_complete_void(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
uint16_t uniffi_pubky_noise_checksum_func_battery_saver_config(void
    
);
uint16_t uniffi_pubky_noise_checksum_func_default_config(void
    
);
uint16_t uniffi_pubky_noise_checksum_func_derive_device_key(void
    
);
uint16_t uniffi_pubky_noise_checksum_func_performance_config(void
    
);
uint16_t uniffi_pubky_noise_checksum_func_public_key_from_secret(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_accept_connection(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_complete_connection(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_connect_client(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_decrypt(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_encrypt(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_get_status(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_initiate_connection(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_list_sessions(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_remove_session(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_restore_state(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_save_state(void
    
);
uint16_t uniffi_pubky_noise_checksum_method_ffinoisemanager_set_status(void
    
);
uint16_t uniffi_pubky_noise_checksum_constructor_ffinoisemanager_new_client(void
    
);
uint16_t uniffi_pubky_noise_checksum_constructor_ffinoisemanager_new_server(void
    
);
uint32_t ffi_pubky_noise_uniffi_contract_version(void
    
);

