// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(PubkyNoiseFFI)
import PubkyNoiseFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pubky_noise_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pubky_noise_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * FFI wrapper around NoiseManager
 *
 * Uses internal Mutex for thread safety across FFI boundary.
 */
public protocol FfiNoiseManagerProtocol : AnyObject {
    
    /**
     * Accept a client connection (server-side handshake).
     *
     * Returns FfiAcceptResult with session_id and response_message to send to client.
     */
    func acceptConnection(firstMsg: Data) throws  -> FfiAcceptResult
    
    /**
     * Complete a client connection after receiving server response.
     */
    func completeConnection(sessionId: String, serverResponse: Data) throws  -> String
    
    /**
     * Initiate a client connection (step 1 of 3-step handshake).
     *
     * Returns the temporary session ID and the first handshake message to send.
     * After sending the message and receiving a response, call `complete_connection`.
     */
    func connectClient(serverPk: Data, hint: String?) throws  -> String
    
    func decrypt(sessionId: String, ciphertext: Data) throws  -> Data
    
    func encrypt(sessionId: String, plaintext: Data) throws  -> Data
    
    func getStatus(sessionId: String)  -> FfiConnectionStatus?
    
    /**
     * Initiate a client connection and get the handshake message.
     *
     * Returns FfiInitiateResult with session_id and first_message to send to server.
     */
    func initiateConnection(serverPk: Data, hint: String?) throws  -> FfiInitiateResult
    
    func listSessions()  -> [String]
    
    func removeSession(sessionId: String) 
    
    func restoreState(state: FfiSessionState) throws 
    
    func saveState(sessionId: String) throws  -> FfiSessionState
    
    func setStatus(sessionId: String, status: FfiConnectionStatus) 
    
}

/**
 * FFI wrapper around NoiseManager
 *
 * Uses internal Mutex for thread safety across FFI boundary.
 */
public class FfiNoiseManager:
    FfiNoiseManagerProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pubky_noise_fn_clone_ffinoisemanager(self.pointer, $0) }
    }

    deinit {
        try! rustCall { uniffi_pubky_noise_fn_free_ffinoisemanager(pointer, $0) }
    }

    
    public static func newClient(config: FfiMobileConfig, clientSeed: Data, clientKid: String, deviceId: Data) throws  -> FfiNoiseManager {
        return FfiNoiseManager(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeFfiNoiseError.lift) {
    uniffi_pubky_noise_fn_constructor_ffinoisemanager_new_client(
        FfiConverterTypeFfiMobileConfig.lower(config),
        FfiConverterData.lower(clientSeed),
        FfiConverterString.lower(clientKid),
        FfiConverterData.lower(deviceId),$0)
})
    }

    
    public static func newServer(config: FfiMobileConfig, serverSeed: Data, serverKid: String, deviceId: Data) throws  -> FfiNoiseManager {
        return FfiNoiseManager(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeFfiNoiseError.lift) {
    uniffi_pubky_noise_fn_constructor_ffinoisemanager_new_server(
        FfiConverterTypeFfiMobileConfig.lower(config),
        FfiConverterData.lower(serverSeed),
        FfiConverterString.lower(serverKid),
        FfiConverterData.lower(deviceId),$0)
})
    }

    

    
    
    /**
     * Accept a client connection (server-side handshake).
     *
     * Returns FfiAcceptResult with session_id and response_message to send to client.
     */
    public func acceptConnection(firstMsg: Data) throws  -> FfiAcceptResult {
        return try  FfiConverterTypeFfiAcceptResult.lift(
            try 
    rustCallWithError(FfiConverterTypeFfiNoiseError.lift) {
    uniffi_pubky_noise_fn_method_ffinoisemanager_accept_connection(self.uniffiClonePointer(), 
        FfiConverterData.lower(firstMsg),$0
    )
}
        )
    }
    /**
     * Complete a client connection after receiving server response.
     */
    public func completeConnection(sessionId: String, serverResponse: Data) throws  -> String {
        return try  FfiConverterString.lift(
            try 
    rustCallWithError(FfiConverterTypeFfiNoiseError.lift) {
    uniffi_pubky_noise_fn_method_ffinoisemanager_complete_connection(self.uniffiClonePointer(), 
        FfiConverterString.lower(sessionId),
        FfiConverterData.lower(serverResponse),$0
    )
}
        )
    }
    /**
     * Initiate a client connection (step 1 of 3-step handshake).
     *
     * Returns the temporary session ID and the first handshake message to send.
     * After sending the message and receiving a response, call `complete_connection`.
     */
    public func connectClient(serverPk: Data, hint: String?) throws  -> String {
        return try  FfiConverterString.lift(
            try 
    rustCallWithError(FfiConverterTypeFfiNoiseError.lift) {
    uniffi_pubky_noise_fn_method_ffinoisemanager_connect_client(self.uniffiClonePointer(), 
        FfiConverterData.lower(serverPk),
        FfiConverterOptionString.lower(hint),$0
    )
}
        )
    }
    public func decrypt(sessionId: String, ciphertext: Data) throws  -> Data {
        return try  FfiConverterData.lift(
            try 
    rustCallWithError(FfiConverterTypeFfiNoiseError.lift) {
    uniffi_pubky_noise_fn_method_ffinoisemanager_decrypt(self.uniffiClonePointer(), 
        FfiConverterString.lower(sessionId),
        FfiConverterData.lower(ciphertext),$0
    )
}
        )
    }
    public func encrypt(sessionId: String, plaintext: Data) throws  -> Data {
        return try  FfiConverterData.lift(
            try 
    rustCallWithError(FfiConverterTypeFfiNoiseError.lift) {
    uniffi_pubky_noise_fn_method_ffinoisemanager_encrypt(self.uniffiClonePointer(), 
        FfiConverterString.lower(sessionId),
        FfiConverterData.lower(plaintext),$0
    )
}
        )
    }
    public func getStatus(sessionId: String)  -> FfiConnectionStatus? {
        return try!  FfiConverterOptionTypeFfiConnectionStatus.lift(
            try! 
    rustCall() {
    
    uniffi_pubky_noise_fn_method_ffinoisemanager_get_status(self.uniffiClonePointer(), 
        FfiConverterString.lower(sessionId),$0
    )
}
        )
    }
    /**
     * Initiate a client connection and get the handshake message.
     *
     * Returns FfiInitiateResult with session_id and first_message to send to server.
     */
    public func initiateConnection(serverPk: Data, hint: String?) throws  -> FfiInitiateResult {
        return try  FfiConverterTypeFfiInitiateResult.lift(
            try 
    rustCallWithError(FfiConverterTypeFfiNoiseError.lift) {
    uniffi_pubky_noise_fn_method_ffinoisemanager_initiate_connection(self.uniffiClonePointer(), 
        FfiConverterData.lower(serverPk),
        FfiConverterOptionString.lower(hint),$0
    )
}
        )
    }
    public func listSessions()  -> [String] {
        return try!  FfiConverterSequenceString.lift(
            try! 
    rustCall() {
    
    uniffi_pubky_noise_fn_method_ffinoisemanager_list_sessions(self.uniffiClonePointer(), $0
    )
}
        )
    }
    public func removeSession(sessionId: String)  {
        try! 
    rustCall() {
    
    uniffi_pubky_noise_fn_method_ffinoisemanager_remove_session(self.uniffiClonePointer(), 
        FfiConverterString.lower(sessionId),$0
    )
}
    }
    public func restoreState(state: FfiSessionState) throws  {
        try 
    rustCallWithError(FfiConverterTypeFfiNoiseError.lift) {
    uniffi_pubky_noise_fn_method_ffinoisemanager_restore_state(self.uniffiClonePointer(), 
        FfiConverterTypeFfiSessionState.lower(state),$0
    )
}
    }
    public func saveState(sessionId: String) throws  -> FfiSessionState {
        return try  FfiConverterTypeFfiSessionState.lift(
            try 
    rustCallWithError(FfiConverterTypeFfiNoiseError.lift) {
    uniffi_pubky_noise_fn_method_ffinoisemanager_save_state(self.uniffiClonePointer(), 
        FfiConverterString.lower(sessionId),$0
    )
}
        )
    }
    public func setStatus(sessionId: String, status: FfiConnectionStatus)  {
        try! 
    rustCall() {
    
    uniffi_pubky_noise_fn_method_ffinoisemanager_set_status(self.uniffiClonePointer(), 
        FfiConverterString.lower(sessionId),
        FfiConverterTypeFfiConnectionStatus.lower(status),$0
    )
}
    }

}

public struct FfiConverterTypeFfiNoiseManager: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiNoiseManager

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiNoiseManager {
        return FfiNoiseManager(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiNoiseManager) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiNoiseManager {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiNoiseManager, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


public func FfiConverterTypeFfiNoiseManager_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiNoiseManager {
    return try FfiConverterTypeFfiNoiseManager.lift(pointer)
}

public func FfiConverterTypeFfiNoiseManager_lower(_ value: FfiNoiseManager) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiNoiseManager.lower(value)
}


/**
 * FFI-safe result for accept_connection
 */
public struct FfiAcceptResult {
    public var sessionId: String
    public var responseMessage: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        sessionId: String, 
        responseMessage: Data) {
        self.sessionId = sessionId
        self.responseMessage = responseMessage
    }
}


extension FfiAcceptResult: Equatable, Hashable {
    public static func ==(lhs: FfiAcceptResult, rhs: FfiAcceptResult) -> Bool {
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.responseMessage != rhs.responseMessage {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sessionId)
        hasher.combine(responseMessage)
    }
}


public struct FfiConverterTypeFfiAcceptResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAcceptResult {
        return
            try FfiAcceptResult(
                sessionId: FfiConverterString.read(from: &buf), 
                responseMessage: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAcceptResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterData.write(value.responseMessage, into: &buf)
    }
}


public func FfiConverterTypeFfiAcceptResult_lift(_ buf: RustBuffer) throws -> FfiAcceptResult {
    return try FfiConverterTypeFfiAcceptResult.lift(buf)
}

public func FfiConverterTypeFfiAcceptResult_lower(_ value: FfiAcceptResult) -> RustBuffer {
    return FfiConverterTypeFfiAcceptResult.lower(value)
}


/**
 * FFI-safe result for initiate_connection
 */
public struct FfiInitiateResult {
    public var sessionId: String
    public var firstMessage: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        sessionId: String, 
        firstMessage: Data) {
        self.sessionId = sessionId
        self.firstMessage = firstMessage
    }
}


extension FfiInitiateResult: Equatable, Hashable {
    public static func ==(lhs: FfiInitiateResult, rhs: FfiInitiateResult) -> Bool {
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.firstMessage != rhs.firstMessage {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sessionId)
        hasher.combine(firstMessage)
    }
}


public struct FfiConverterTypeFfiInitiateResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiInitiateResult {
        return
            try FfiInitiateResult(
                sessionId: FfiConverterString.read(from: &buf), 
                firstMessage: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: FfiInitiateResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterData.write(value.firstMessage, into: &buf)
    }
}


public func FfiConverterTypeFfiInitiateResult_lift(_ buf: RustBuffer) throws -> FfiInitiateResult {
    return try FfiConverterTypeFfiInitiateResult.lift(buf)
}

public func FfiConverterTypeFfiInitiateResult_lower(_ value: FfiInitiateResult) -> RustBuffer {
    return FfiConverterTypeFfiInitiateResult.lower(value)
}


/**
 * FFI-safe mobile configuration wrapper
 */
public struct FfiMobileConfig {
    public var autoReconnect: Bool
    public var maxReconnectAttempts: UInt32
    public var reconnectDelayMs: UInt64
    public var batterySaver: Bool
    public var chunkSize: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        autoReconnect: Bool, 
        maxReconnectAttempts: UInt32, 
        reconnectDelayMs: UInt64, 
        batterySaver: Bool, 
        chunkSize: UInt64) {
        self.autoReconnect = autoReconnect
        self.maxReconnectAttempts = maxReconnectAttempts
        self.reconnectDelayMs = reconnectDelayMs
        self.batterySaver = batterySaver
        self.chunkSize = chunkSize
    }
}


extension FfiMobileConfig: Equatable, Hashable {
    public static func ==(lhs: FfiMobileConfig, rhs: FfiMobileConfig) -> Bool {
        if lhs.autoReconnect != rhs.autoReconnect {
            return false
        }
        if lhs.maxReconnectAttempts != rhs.maxReconnectAttempts {
            return false
        }
        if lhs.reconnectDelayMs != rhs.reconnectDelayMs {
            return false
        }
        if lhs.batterySaver != rhs.batterySaver {
            return false
        }
        if lhs.chunkSize != rhs.chunkSize {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(autoReconnect)
        hasher.combine(maxReconnectAttempts)
        hasher.combine(reconnectDelayMs)
        hasher.combine(batterySaver)
        hasher.combine(chunkSize)
    }
}


public struct FfiConverterTypeFfiMobileConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMobileConfig {
        return
            try FfiMobileConfig(
                autoReconnect: FfiConverterBool.read(from: &buf), 
                maxReconnectAttempts: FfiConverterUInt32.read(from: &buf), 
                reconnectDelayMs: FfiConverterUInt64.read(from: &buf), 
                batterySaver: FfiConverterBool.read(from: &buf), 
                chunkSize: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMobileConfig, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.autoReconnect, into: &buf)
        FfiConverterUInt32.write(value.maxReconnectAttempts, into: &buf)
        FfiConverterUInt64.write(value.reconnectDelayMs, into: &buf)
        FfiConverterBool.write(value.batterySaver, into: &buf)
        FfiConverterUInt64.write(value.chunkSize, into: &buf)
    }
}


public func FfiConverterTypeFfiMobileConfig_lift(_ buf: RustBuffer) throws -> FfiMobileConfig {
    return try FfiConverterTypeFfiMobileConfig.lift(buf)
}

public func FfiConverterTypeFfiMobileConfig_lower(_ value: FfiMobileConfig) -> RustBuffer {
    return FfiConverterTypeFfiMobileConfig.lower(value)
}


/**
 * FFI-safe session state wrapper.
 */
public struct FfiSessionState {
    public var sessionId: String
    public var peerStaticPk: Data
    public var writeCounter: UInt64
    public var readCounter: UInt64
    public var status: FfiConnectionStatus

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        sessionId: String, 
        peerStaticPk: Data, 
        writeCounter: UInt64, 
        readCounter: UInt64, 
        status: FfiConnectionStatus) {
        self.sessionId = sessionId
        self.peerStaticPk = peerStaticPk
        self.writeCounter = writeCounter
        self.readCounter = readCounter
        self.status = status
    }
}


extension FfiSessionState: Equatable, Hashable {
    public static func ==(lhs: FfiSessionState, rhs: FfiSessionState) -> Bool {
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.peerStaticPk != rhs.peerStaticPk {
            return false
        }
        if lhs.writeCounter != rhs.writeCounter {
            return false
        }
        if lhs.readCounter != rhs.readCounter {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sessionId)
        hasher.combine(peerStaticPk)
        hasher.combine(writeCounter)
        hasher.combine(readCounter)
        hasher.combine(status)
    }
}


public struct FfiConverterTypeFfiSessionState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSessionState {
        return
            try FfiSessionState(
                sessionId: FfiConverterString.read(from: &buf), 
                peerStaticPk: FfiConverterData.read(from: &buf), 
                writeCounter: FfiConverterUInt64.read(from: &buf), 
                readCounter: FfiConverterUInt64.read(from: &buf), 
                status: FfiConverterTypeFfiConnectionStatus.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSessionState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterData.write(value.peerStaticPk, into: &buf)
        FfiConverterUInt64.write(value.writeCounter, into: &buf)
        FfiConverterUInt64.write(value.readCounter, into: &buf)
        FfiConverterTypeFfiConnectionStatus.write(value.status, into: &buf)
    }
}


public func FfiConverterTypeFfiSessionState_lift(_ buf: RustBuffer) throws -> FfiSessionState {
    return try FfiConverterTypeFfiSessionState.lift(buf)
}

public func FfiConverterTypeFfiSessionState_lower(_ value: FfiSessionState) -> RustBuffer {
    return FfiConverterTypeFfiSessionState.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * FFI-safe connection status wrapper
 */
public enum FfiConnectionStatus {
    
    case connected
    case reconnecting
    case disconnected
    case error
}

public struct FfiConverterTypeFfiConnectionStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiConnectionStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiConnectionStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .connected
        
        case 2: return .reconnecting
        
        case 3: return .disconnected
        
        case 4: return .error
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiConnectionStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .connected:
            writeInt(&buf, Int32(1))
        
        
        case .reconnecting:
            writeInt(&buf, Int32(2))
        
        
        case .disconnected:
            writeInt(&buf, Int32(3))
        
        
        case .error:
            writeInt(&buf, Int32(4))
        
        }
    }
}


public func FfiConverterTypeFfiConnectionStatus_lift(_ buf: RustBuffer) throws -> FfiConnectionStatus {
    return try FfiConverterTypeFfiConnectionStatus.lift(buf)
}

public func FfiConverterTypeFfiConnectionStatus_lower(_ value: FfiConnectionStatus) -> RustBuffer {
    return FfiConverterTypeFfiConnectionStatus.lower(value)
}


extension FfiConnectionStatus: Equatable, Hashable {}




public enum FfiNoiseError {

    
    
    case Ring(
        message: String
    )
    case Pkarr(
        message: String
    )
    case Snow(
        message: String
    )
    case Serde(
        message: String
    )
    case IdentityVerify
    case RemoteStaticMissing
    case Policy(
        message: String
    )
    case InvalidPeerKey
    case Network(
        message: String
    )
    case Timeout(
        message: String
    )
    case Storage(
        message: String
    )
    case Decryption(
        message: String
    )
    case RateLimited(
        message: String
    )
    case MaxSessionsExceeded
    case SessionExpired(
        message: String
    )
    case ConnectionReset(
        message: String
    )
    case Other(
        message: String
    )

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeFfiNoiseError.lift(error)
    }
}


public struct FfiConverterTypeFfiNoiseError: FfiConverterRustBuffer {
    typealias SwiftType = FfiNoiseError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiNoiseError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Ring(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Pkarr(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Snow(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Serde(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .IdentityVerify
        case 6: return .RemoteStaticMissing
        case 7: return .Policy(
            message: try FfiConverterString.read(from: &buf)
            )
        case 8: return .InvalidPeerKey
        case 9: return .Network(
            message: try FfiConverterString.read(from: &buf)
            )
        case 10: return .Timeout(
            message: try FfiConverterString.read(from: &buf)
            )
        case 11: return .Storage(
            message: try FfiConverterString.read(from: &buf)
            )
        case 12: return .Decryption(
            message: try FfiConverterString.read(from: &buf)
            )
        case 13: return .RateLimited(
            message: try FfiConverterString.read(from: &buf)
            )
        case 14: return .MaxSessionsExceeded
        case 15: return .SessionExpired(
            message: try FfiConverterString.read(from: &buf)
            )
        case 16: return .ConnectionReset(
            message: try FfiConverterString.read(from: &buf)
            )
        case 17: return .Other(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiNoiseError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Ring(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Pkarr(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Snow(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Serde(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case .IdentityVerify:
            writeInt(&buf, Int32(5))
        
        
        case .RemoteStaticMissing:
            writeInt(&buf, Int32(6))
        
        
        case let .Policy(message):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(message, into: &buf)
            
        
        case .InvalidPeerKey:
            writeInt(&buf, Int32(8))
        
        
        case let .Network(message):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Timeout(message):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Storage(message):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Decryption(message):
            writeInt(&buf, Int32(12))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .RateLimited(message):
            writeInt(&buf, Int32(13))
            FfiConverterString.write(message, into: &buf)
            
        
        case .MaxSessionsExceeded:
            writeInt(&buf, Int32(14))
        
        
        case let .SessionExpired(message):
            writeInt(&buf, Int32(15))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .ConnectionReset(message):
            writeInt(&buf, Int32(16))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Other(message):
            writeInt(&buf, Int32(17))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension FfiNoiseError: Equatable, Hashable {}

extension FfiNoiseError: Error { }

fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionTypeFfiConnectionStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiConnectionStatus?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiConnectionStatus.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiConnectionStatus.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
public func batterySaverConfig()  -> FfiMobileConfig {
    return try!  FfiConverterTypeFfiMobileConfig.lift(
        try! rustCall() {
    uniffi_pubky_noise_fn_func_battery_saver_config($0)
}
    )
}
public func defaultConfig()  -> FfiMobileConfig {
    return try!  FfiConverterTypeFfiMobileConfig.lift(
        try! rustCall() {
    uniffi_pubky_noise_fn_func_default_config($0)
}
    )
}
public func deriveDeviceKey(seed: Data, deviceId: Data, epoch: UInt32)  -> Data {
    return try!  FfiConverterData.lift(
        try! rustCall() {
    uniffi_pubky_noise_fn_func_derive_device_key(
        FfiConverterData.lower(seed),
        FfiConverterData.lower(deviceId),
        FfiConverterUInt32.lower(epoch),$0)
}
    )
}
public func performanceConfig()  -> FfiMobileConfig {
    return try!  FfiConverterTypeFfiMobileConfig.lift(
        try! rustCall() {
    uniffi_pubky_noise_fn_func_performance_config($0)
}
    )
}
public func publicKeyFromSecret(secret: Data)  -> Data {
    return try!  FfiConverterData.lift(
        try! rustCall() {
    uniffi_pubky_noise_fn_func_public_key_from_secret(
        FfiConverterData.lower(secret),$0)
}
    )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 25
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pubky_noise_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pubky_noise_checksum_func_battery_saver_config() != 51578) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_func_default_config() != 63887) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_func_derive_device_key() != 38295) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_func_performance_config() != 613) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_func_public_key_from_secret() != 41381) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_accept_connection() != 42119) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_complete_connection() != 48304) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_connect_client() != 41850) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_decrypt() != 59225) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_encrypt() != 20027) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_get_status() != 26415) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_initiate_connection() != 31127) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_list_sessions() != 40155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_remove_session() != 60738) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_restore_state() != 7835) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_save_state() != 56444) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_method_ffinoisemanager_set_status() != 31618) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_constructor_ffinoisemanager_new_client() != 39573) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pubky_noise_checksum_constructor_ffinoisemanager_new_server() != 15865) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}