name: iOS Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.0"

      - name: Clean Package.resolved
        run: |
          rm -f Bitkit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved || true

      - name: List Schemes
        run: xcodebuild -list -project Bitkit.xcodeproj

      - name: Build and Test
        run: |
          xcodebuild clean build test \
            -project Bitkit.xcodeproj \
            -scheme Bitkit \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
            -configuration Debug \
            -enableCodeCoverage NO \
            -allowProvisioningUpdates \
            -skipPackagePluginValidation \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
            | xcpretty && exit ${PIPESTATUS[0]}
