name: iOS Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.0"

      - name: Build and Test
        run: |
          xcodebuild test \
            -scheme Bitkit \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
            | xcpretty && exit ${PIPESTATUS[0]}
