name: iOS Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  test:
    name: Run Tests
    runs-on: [self-hosted, macOS]
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Reset testing enviroment
        continue-on-error: true
        timeout-minutes: 10
        run: |
          pkill -f react-native || echo 0
          pkill -f Simulator || echo 0
          rm -rf /tmp/lock/*
      # cd docker && docker compose down -v -t 300

      - name: Install xcbeautify
        run: |
          brew install xcbeautify

      - name: Pre-start simulator
        run: |
          xcrun simctl boot "iPhone 16" || true

      - name: Run tests
        run: |
          set -o pipefail && xcodebuild test \
            -scheme Bitkit \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -enableCodeCoverage YES \
            -parallel-testing-enabled NO \
            | xcbeautify --report junit

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
